In [61]:
# This is the datascience module from Berkeley
# https://github.com/data-8/datascience

from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [62]:
url = 'https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/asrh/nc-est2015-agesex-res.csv'
full = Table.read_table(url)
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015
0    | 0    | 3944153       | 3944160           | 3951330         | 3963087         | 3926540         | 3931141         | 3949775         | 3978038
0    | 1    | 3978070       | 3978090           | 3957888         | 3966551         | 3977939         | 3942872         | 3949776         | 3968564
0    | 2    | 4096929       | 4096939           | 4090862         | 3971565         | 3980095         | 3992720         | 3959664         | 3966583
0    | 3    | 4119040       | 4119051           | 4111920         | 4102470         | 3983157         | 3992734         | 4007079         | 3974061
0    | 4    | 4063170       | 4063186           | 4077551         | 4122294         | 4112849         | 3994449         | 4005716         | 4020035
0    | 5    | 4056858       | 4056872           | 4064653         | 4087709         | 4132242         | 4123626         | 4006900         | 4018158
0    | 6    | 4066381       | 4066412           | 4073013         | 4074993         | 4097605         | 4142916         | 4135930         | 4019207
0    | 7    | 4030579       | 4030594           | 4043046         | 4083225         | 4084913         | 4108349         | 4155326         | 4148360
0    | 8    | 4046486       | 4046497           | 4025604         | 4053203         | 4093177         | 4095711         | 4120903         | 4167887
0    | 9    | 4148353       | 4148369           | 4125415         | 4035710         | 4063152         | 4104072         | 4108349         | 4133564
... (296 rows omitted)

In [63]:
partial = full.select('SEX', 'AGE', 4, 9)
partial

SEX  | AGE  | POPESTIMATE2010 | POPESTIMATE2015
0    | 0    | 3951330         | 3978038
0    | 1    | 3957888         | 3968564
0    | 2    | 4090862         | 3966583
0    | 3    | 4111920         | 3974061
0    | 4    | 4077551         | 4020035
0    | 5    | 4064653         | 4018158
0    | 6    | 4073013         | 4019207
0    | 7    | 4043046         | 4148360
0    | 8    | 4025604         | 4167887
0    | 9    | 4125415         | 4133564
... (296 rows omitted)

In [64]:
partial.relabel(2, '2010')

SEX  | AGE  | 2010    | POPESTIMATE2015
0    | 0    | 3951330 | 3978038
0    | 1    | 3957888 | 3968564
0    | 2    | 4090862 | 3966583
0    | 3    | 4111920 | 3974061
0    | 4    | 4077551 | 4020035
0    | 5    | 4064653 | 4018158
0    | 6    | 4073013 | 4019207
0    | 7    | 4043046 | 4148360
0    | 8    | 4025604 | 4167887
0    | 9    | 4125415 | 4133564
... (296 rows omitted)

In [65]:
us_pop = partial.relabel(2, '2010').relabel(3, '2015')
us_pop

SEX  | AGE  | 2010    | 2015
0    | 0    | 3951330 | 3978038
0    | 1    | 3957888 | 3968564
0    | 2    | 4090862 | 3966583
0    | 3    | 4111920 | 3974061
0    | 4    | 4077551 | 4020035
0    | 5    | 4064653 | 4018158
0    | 6    | 4073013 | 4019207
0    | 7    | 4043046 | 4148360
0    | 8    | 4025604 | 4167887
0    | 9    | 4125415 | 4133564
... (296 rows omitted)

In [66]:
us_pop.set_format([2, 3], NumberFormatter)

SEX  | AGE  | 2010      | 2015
0    | 0    | 3,951,330 | 3,978,038
0    | 1    | 3,957,888 | 3,968,564
0    | 2    | 4,090,862 | 3,966,583
0    | 3    | 4,111,920 | 3,974,061
0    | 4    | 4,077,551 | 4,020,035
0    | 5    | 4,064,653 | 4,018,158
0    | 6    | 4,073,013 | 4,019,207
0    | 7    | 4,043,046 | 4,148,360
0    | 8    | 4,025,604 | 4,167,887
0    | 9    | 4,125,415 | 4,133,564
... (296 rows omitted)

In [67]:
us_pop.column('2010')

array([  3951330,   3957888,   4090862,   4111920,   4077551,   4064653,
         4073013,   4043046,   4025604,   4125415,   4187062,   4115511,
         4113279,   4119666,   4145614,   4231002,   4313252,   4376367,
         4491005,   4571411,   4568517,   4387956,   4287005,   4217228,
         4243602,   4289428,   4160806,   4237026,   4247541,   4210286,
         4304239,   4042516,   3967602,   3933581,   3822189,   3948335,
         3830199,   3896766,   4080228,   4324463,   4387480,   4163478,
         4082712,   4093844,   4178508,   4438559,   4529716,   4535473,
         4534663,   4599098,   4646231,   4498974,   4480584,   4439403,
         4288447,   4258970,   4093136,   3946518,   3802447,   3694254,
         3616721,   3520109,   3495059,   3652167,   2706055,   2678525,
         2621335,   2693707,   2359816,   2167830,   2062577,   1953607,
         1883820,   1750304,   1685995,   1631878,   1481680,   1449173,
         1402182,   1354912,   1319725,   1212603, 

In [68]:
us_pop.column('2010')[:10]

array([3951330, 3957888, 4090862, 4111920, 4077551, 4064653, 4073013,
       4043046, 4025604, 4125415])

In [69]:
difference = us_pop.column('2015') - us_pop.column('2010')
difference

array([   26708,    10676,  -124279,  -137859,   -57516,   -46495,
         -53806,   105314,   142283,     8149,   -65773,    14817,
         -12258,   -35360,    39772,    18740,  -128956,  -182081,
        -273010,  -308827,  -205077,    68834,   242467,   435038,
         493743,   440136,   383610,   202740,   117128,   172853,
         112970,   235717,   376012,   408173,   472649,   431069,
         278576,   131637,   -93087,  -453601,  -397641,  -298250,
        -158454,     6864,   156657,   -49214,  -369143,  -461788,
        -456974,  -446546,  -245943,   -19310,    -6240,    24091,
         228080,   294415,   305984,   424727,   518075,   469416,
         509071,   434492,   306876,     -774,   830101,   771518,
         722799,   610480,  1076541,   364917,   429913,   467584,
         585785,   395748,   267716,   207945,   240361,   189912,
          98631,    67159,    31471,   -11559,    -9403,     1122,
          28568,    42010,    24532,    53443,    53098,    50

In [70]:
us_pop.with_column(
    'Differences', difference
)

SEX  | AGE  | 2010      | 2015      | Differences
0    | 0    | 3,951,330 | 3,978,038 | 26708
0    | 1    | 3,957,888 | 3,968,564 | 10676
0    | 2    | 4,090,862 | 3,966,583 | -124279
0    | 3    | 4,111,920 | 3,974,061 | -137859
0    | 4    | 4,077,551 | 4,020,035 | -57516
0    | 5    | 4,064,653 | 4,018,158 | -46495
0    | 6    | 4,073,013 | 4,019,207 | -53806
0    | 7    | 4,043,046 | 4,148,360 | 105314
0    | 8    | 4,025,604 | 4,167,887 | 142283
0    | 9    | 4,125,415 | 4,133,564 | 8149
... (296 rows omitted)

In [71]:
census = us_pop.with_columns(
    'Difference', difference,
    'Total Growth', difference / us_pop.column('2010')
)
census

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth
0    | 0    | 3,951,330 | 3,978,038 | 26708      | 0.00675924
0    | 1    | 3,957,888 | 3,968,564 | 10676      | 0.0026974
0    | 2    | 4,090,862 | 3,966,583 | -124279    | -0.0303797
0    | 3    | 4,111,920 | 3,974,061 | -137859    | -0.0335267
0    | 4    | 4,077,551 | 4,020,035 | -57516     | -0.0141055
0    | 5    | 4,064,653 | 4,018,158 | -46495     | -0.0114389
0    | 6    | 4,073,013 | 4,019,207 | -53806     | -0.0132104
0    | 7    | 4,043,046 | 4,148,360 | 105314     | 0.0260482
0    | 8    | 4,025,604 | 4,167,887 | 142283     | 0.0353445
0    | 9    | 4,125,415 | 4,133,564 | 8149       | 0.00197532
... (296 rows omitted)

In [72]:
census.set_format('Total Growth', PercentFormatter)

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth
0    | 0    | 3,951,330 | 3,978,038 | 26708      | 0.68%
0    | 1    | 3,957,888 | 3,968,564 | 10676      | 0.27%
0    | 2    | 4,090,862 | 3,966,583 | -124279    | -3.04%
0    | 3    | 4,111,920 | 3,974,061 | -137859    | -3.35%
0    | 4    | 4,077,551 | 4,020,035 | -57516     | -1.41%
0    | 5    | 4,064,653 | 4,018,158 | -46495     | -1.14%
0    | 6    | 4,073,013 | 4,019,207 | -53806     | -1.32%
0    | 7    | 4,043,046 | 4,148,360 | 105314     | 2.60%
0    | 8    | 4,025,604 | 4,167,887 | 142283     | 3.53%
0    | 9    | 4,125,415 | 4,133,564 | 8149       | 0.20%
... (296 rows omitted)

In [73]:
census.set_format('Difference', NumberFormatter)

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth
0    | 0    | 3,951,330 | 3,978,038 | 26,708     | 0.68%
0    | 1    | 3,957,888 | 3,968,564 | 10,676     | 0.27%
0    | 2    | 4,090,862 | 3,966,583 | -124,279   | -3.04%
0    | 3    | 4,111,920 | 3,974,061 | -137,859   | -3.35%
0    | 4    | 4,077,551 | 4,020,035 | -57,516    | -1.41%
0    | 5    | 4,064,653 | 4,018,158 | -46,495    | -1.14%
0    | 6    | 4,073,013 | 4,019,207 | -53,806    | -1.32%
0    | 7    | 4,043,046 | 4,148,360 | 105,314    | 2.60%
0    | 8    | 4,025,604 | 4,167,887 | 142,283    | 3.53%
0    | 9    | 4,125,415 | 4,133,564 | 8,149      | 0.20%
... (296 rows omitted)

In [74]:
census.sort('Difference')

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth
0    | 47   | 4,535,473 | 4,073,685 | -461,788   | -10.18%
0    | 48   | 4,534,663 | 4,077,689 | -456,974   | -10.08%
0    | 39   | 4,324,463 | 3,870,862 | -453,601   | -10.49%
0    | 49   | 4,599,098 | 4,152,552 | -446,546   | -9.71%
0    | 40   | 4,387,480 | 3,989,839 | -397,641   | -9.06%
0    | 46   | 4,529,716 | 4,160,573 | -369,143   | -8.15%
0    | 19   | 4,571,411 | 4,262,584 | -308,827   | -6.76%
0    | 41   | 4,163,478 | 3,865,228 | -298,250   | -7.16%
0    | 18   | 4,491,005 | 4,217,995 | -273,010   | -6.08%
0    | 50   | 4,646,231 | 4,400,288 | -245,943   | -5.29%
... (296 rows omitted)

In [75]:
census_sorted = census.sort('Difference', descending = True)
census_sorted

SEX  | AGE  | 2010        | 2015        | Difference | Total Growth
0    | 999  | 309,346,863 | 321,418,820 | 12,071,957 | 3.90%
1    | 999  | 152,088,043 | 158,229,297 | 6,141,254  | 4.04%
2    | 999  | 157,258,820 | 163,189,523 | 5,930,703  | 3.77%
0    | 68   | 2,359,816   | 3,436,357   | 1,076,541  | 45.62%
0    | 64   | 2,706,055   | 3,536,156   | 830,101    | 30.68%
0    | 65   | 2,678,525   | 3,450,043   | 771,518    | 28.80%
0    | 66   | 2,621,335   | 3,344,134   | 722,799    | 27.57%
0    | 67   | 2,693,707   | 3,304,187   | 610,480    | 22.66%
0    | 72   | 1,883,820   | 2,469,605   | 585,785    | 31.10%
2    | 68   | 1,254,117   | 1,812,428   | 558,311    | 44.52%
... (296 rows omitted)

In [76]:
census_sorted.row(0)

Row(SEX=0, AGE=999, 2010=309346863, 2015=321418820, Difference=12071957, Total Growth=0.039024016222204264)

In [77]:
after = census_sorted.row(0)[3]
after

321418820

In [78]:
before = census_sorted.row(0)[2]
before

309346863

In [79]:
annual_growth_rate = (after / before) **(1/5) - 1
annual_growth_rate

0.007685750230353783

In [80]:
print('Annual growth rate: %.3f Percent' %(annual_growth_rate * 100))

Annual growth rate: 0.769 Percent


In [81]:
census

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth
0    | 0    | 3,951,330 | 3,978,038 | 26,708     | 0.68%
0    | 1    | 3,957,888 | 3,968,564 | 10,676     | 0.27%
0    | 2    | 4,090,862 | 3,966,583 | -124,279   | -3.04%
0    | 3    | 4,111,920 | 3,974,061 | -137,859   | -3.35%
0    | 4    | 4,077,551 | 4,020,035 | -57,516    | -1.41%
0    | 5    | 4,064,653 | 4,018,158 | -46,495    | -1.14%
0    | 6    | 4,073,013 | 4,019,207 | -53,806    | -1.32%
0    | 7    | 4,043,046 | 4,148,360 | 105,314    | 2.60%
0    | 8    | 4,025,604 | 4,167,887 | 142,283    | 3.53%
0    | 9    | 4,125,415 | 4,133,564 | 8,149      | 0.20%
... (296 rows omitted)

In [82]:
after  = census.column(3)
before = census.column(2)
years_passed = 5

annual_growth_rate = (after / before) ** (1 / years_passed) - 1
annual_growth_rate[:5]


array([ 0.00134821,  0.0005389 , -0.00615114, -0.00679711, -0.00283716])

In [83]:
census = census.with_column(
    'Annual Growth Rate', annual_growth_rate
).set_format(6, PercentFormatter)
census

SEX  | AGE  | 2010      | 2015      | Difference | Total Growth | Annual Growth Rate
0    | 0    | 3,951,330 | 3,978,038 | 26,708     | 0.68%        | 0.13%
0    | 1    | 3,957,888 | 3,968,564 | 10,676     | 0.27%        | 0.05%
0    | 2    | 4,090,862 | 3,966,583 | -124,279   | -3.04%       | -0.62%
0    | 3    | 4,111,920 | 3,974,061 | -137,859   | -3.35%       | -0.68%
0    | 4    | 4,077,551 | 4,020,035 | -57,516    | -1.41%       | -0.28%
0    | 5    | 4,064,653 | 4,018,158 | -46,495    | -1.14%       | -0.23%
0    | 6    | 4,073,013 | 4,019,207 | -53,806    | -1.32%       | -0.27%
0    | 7    | 4,043,046 | 4,148,360 | 105,314    | 2.60%        | 0.52%
0    | 8    | 4,025,604 | 4,167,887 | 142,283    | 3.53%        | 0.70%
0    | 9    | 4,125,415 | 4,133,564 | 8,149      | 0.20%        | 0.04%
... (296 rows omitted)

In [84]:
census.sort('Difference', descending=True)

SEX  | AGE  | 2010        | 2015        | Difference | Total Growth | Annual Growth Rate
0    | 999  | 309,346,863 | 321,418,820 | 12,071,957 | 3.90%        | 0.77%
1    | 999  | 152,088,043 | 158,229,297 | 6,141,254  | 4.04%        | 0.79%
2    | 999  | 157,258,820 | 163,189,523 | 5,930,703  | 3.77%        | 0.74%
0    | 68   | 2,359,816   | 3,436,357   | 1,076,541  | 45.62%       | 7.81%
0    | 64   | 2,706,055   | 3,536,156   | 830,101    | 30.68%       | 5.50%
0    | 65   | 2,678,525   | 3,450,043   | 771,518    | 28.80%       | 5.19%
0    | 66   | 2,621,335   | 3,344,134   | 722,799    | 27.57%       | 4.99%
0    | 67   | 2,693,707   | 3,304,187   | 610,480    | 22.66%       | 4.17%
0    | 72   | 1,883,820   | 2,469,605   | 585,785    | 31.10%       | 5.56%
2    | 68   | 1,254,117   | 1,812,428   | 558,311    | 44.52%       | 7.64%
... (296 rows omitted)